name: Flutter Build APK

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Java 17
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Set up Stable Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          cache: true

      - name: Execute Solid Compiling Engine
        run: |
          flutter clean
          flutter pub get
          flutter build apk --debug

      - name: Upload Clean Protected APK
        uses: actions/upload-artifact@v4
        with:
          name: PopProof-Debug-APK
          path: build/app/outputs/flutter-apk/app-debug.apk
